export default {
  "APP_SELECT_PRODUCT_VIEW": "",
  "APP_THRESHOLD_UPDATES_VIEW": "",
  "APP_SAVE_THRESHOLD_VIEW": "MERCHANDISING_ADMIN OR MERCHANDISING_VIEW",
  "APP_JOB_VIEW": "",
  "APP_JOB_UPDATE": "MERCHANDISING_ADMIN OR MERCHANDISING_VIEW",
  "APP_THRESHOLD_RULE_UPDATE": "MERCHANDISING_ADMIN OR MERCHANDISING_VIEW",
  "MERCHANDISING_ADMIN": "MERCHANDISING_ADMIN",
  "THRESHOLD_APP_VIEW": "THRESHOLD_APP_VIEW"
} as any 