export const SN_CHANNEL = 'channel'
export const CHANNEL_INVENTORY_CHANNELS_UPDATED = SN_CHANNEL + '/INVENTORY_CHANNELS_UPDATED'
export const CHANNEL_GROUP_CONFIG_FACILITIES_UPDATED = SN_CHANNEL + '/GROUP_CONFIG_FACILITIES_UPDATED'
export const CHANNEL_CLEARED = SN_CHANNEL + "/CLEARED"