export const SN_PRODUCT = 'product'
export const PRODUCT_LIST_UPDATED = SN_PRODUCT + '/LIST_UPDATED'
export const PRODUCT_APPLIED_FILTERS_UPDATED = SN_PRODUCT + '/APPLIED_FILTERS_UPDATED'
export const PRODUCT_QUERY_UPDATED = SN_PRODUCT + '/QUERY_UPDATED'
